Radical update of mesh_gl plugin
UniStuttgart-VISUS/megamol pull request #1093
Opened 2022-07-29 13:44 UTC by invor

Removes call/chaining concept for GPU data (meshes, materials, render tasks) in favor of monolithic mesh rendering modules. Still makes use of the existing collection classes for GPU data internally. New base classes are added for mesh renderers to provide a framework for implementing new mesh renderers with as little effort as possible.

## Summary of Changes

- Remove calls for GPU mesh, material and render task data
- Remove abstract base classes for GPU mesh, material and render task modules with chaining
- Add new base classes for monolithic rendering modules 
- Add modules for rendering gltf files with deferred shading and obj files with simple forward shading

## References and Context

## Test Instructions

2022-08-02 14:57 UTC, invor commented
/format

2022-08-03 10:28 UTC, invor commented
/format

2022-08-03 15:19 UTC, invor commented
/format

2022-08-03 15:26 UTC, moritz-h requested changes

2022-08-03 15:26 UTC, moritz-h commented on plugins/mesh_gl/include/mesh_gl/MeshCalls_gl.h
Why not just delete that file?

2022-08-03 15:32 UTC, invor commented on plugins/mesh_gl/include/mesh_gl/MeshCalls_gl.h
Happy?

2022-08-03 15:33 UTC, moritz-h approved these changes, later dismissed

2022-08-03 18:43 UTC, moritz-h approved these changes

2022-08-03 18:44 UTC, merged