Screenshots are as good as project files now
UniStuttgart-VISUS/megamol pull request #326
Opened 2019-07-15 17:12 UTC by reinago

- fix: trailing zero in EXIF
- fix: multi-line parameter values in EXIF
- use EXIF data as lua project for reproducibility goodness

2019-07-16 09:44 UTC, braunms commented on core/src/CoreInstance.cpp
> +                    }
The **png_infop** could be cleaned up here with:
**png_destroy_info_struct (png, &info);**

2019-07-16 09:45 UTC, braunms commented on core/src/CoreInstance.cpp
> +                // TODO: dispose exif_data buffer...?
What are the arguments against **delete [] exif_data;** ?

2019-07-16 09:46 UTC, reinago commented on core/src/CoreInstance.cpp
> +                    }
that code should already be there...

2019-07-16 09:47 UTC, reinago commented on core/src/CoreInstance.cpp
> +                // TODO: dispose exif_data buffer...?
I did not have time to test that. I have no idea whether delete or delete[] is appropriate here.

2019-07-17 09:12 UTC, gralkapk requested changes

2019-07-17 09:12 UTC, gralkapk commented on core/src/CoreInstance.cpp
> +                            this->loadedLuaProjects.Add(
Why VISlib :(

2019-07-17 09:12 UTC, gralkapk commented on core/src/CoreInstance.cpp
> +            FILE* fp = fopen(W2A(filename.PeekBuffer()), "rb");
Isn't that the only difference to the above version?

2019-07-17 11:45 UTC, braunms commented on core/src/view/special/ScreenShooter.cpp
> +                            confParams << "mmSetParamValue(\"" << slot->FullName() << "\",[[" << val << "]])\n";
Unescaped quotes don't need and even shouldn't be escaped any more when multiline string delimiter ist used (Escaped quotes break JSON string, e.g.). And delimiter shouldn't be "[[" since this can be part of a JSNON string, too (use e.g. "[=[" and "]=]"?).

2019-07-17 16:49 UTC, tobiasrau approved these changes

2019-07-18 13:18 UTC, merged