SphereRenderer
UniStuttgart-VISUS/megamol pull request #386
Opened 2019-08-13 16:05 UTC by braunms

- Added FlagStorage support for all render modes
- Consolidated redundant shader code
- Added Ambient Occlusion to regression test
- Some code formatting and cleanup
- Table2Particles: Considering radius for bbox size calculation
- Transformed color param in ClippingPlane to 'real' ColorParam

2019-08-16 14:54 UTC, reinago commented
can we consolidate this even more? I see many blah_attributes and they are pretty similar. also sometimes the blah start still contains attributes, doesn't it?

2019-08-20 11:25 UTC, tobiasrau requested changes

2019-08-20 11:25 UTC, tobiasrau commented on core/Shaders/sphere/splat_fragment_mainstart.glsl
> +void main(void) {
Could this also become a simple_mainstart?

2019-08-20 12:23 UTC, braunms commented on core/Shaders/sphere/splat_fragment_mainstart.glsl
> +void main(void) {
Jupp, good point, done in commit a31ee39.

2019-08-21 14:25 UTC, tobiasrau approved these changes

2019-08-22 17:19 UTC, tobiasrau requested changes
1|[SphereRenderer] Unable to compile sphere shader (@compile vertex): 0:16(2): error: vertex shader input / attribute cannot have array type in GLSL 1.30 (GLSL 1.50 required)

2019-08-23 10:14 UTC, merged