NGMesh and ArchVis Plugins
UniStuttgart-VISUS/megamol pull request #44
Opened 2017-09-19 15:49 UTC by invor

NGMesh Plugin: A modern renderer for arbitrary meshes. All data (shader, mesh, draw commands, shader parameters) is prepared and supplied by the data source. An example/template for such a datasource will be included.

ArchVis Plugin: Plugin for scientific architectural visualizations in the context of SFB1244.

2017-09-20 09:01 UTC, reinago requested changes
- it does not work yet, right? why merge now?
- Readme.md please if you merge
- I don't really like Pascal-style brackets ;)

2017-09-20 09:01 UTC, reinago commented on plugins/ng_mesh/include/ng_mesh/CallNGMeshRenderBatches.h
> +				static uint32_t shaderUpdateBit()			{ return 0x1; }
why? plus it's not even inline. enums work okay, don't they?

2017-09-20 09:01 UTC, reinago commented on plugins/ng_mesh/include/ng_mesh/CallNGMeshRenderBatches.h
> +						shader_prgms = reinterpret_cast<ShaderPrgmData*>(raw_buffer);
no offsets?

2017-09-20 09:01 UTC, reinago commented on plugins/ng_mesh/src/NGMeshRenderer.cpp
> +		/*
?

2017-09-20 17:32 UTC, invor commented on plugins/ng_mesh/include/ng_mesh/CallNGMeshRenderBatches.h
> +						shader_prgms = reinterpret_cast<ShaderPrgmData*>(raw_buffer);
Fixed in f8bfeb7

2017-09-20 17:35 UTC, invor commented on plugins/ng_mesh/src/NGMeshRenderer.cpp
> +		/*
What seems to be the problem? glMultiDrawElementsIndirect requires draw commands buffer (SSBO in this case) + geometry to work with given by a vertex array object.

2017-09-20 17:39 UTC, invor commented on plugins/ng_mesh/include/ng_mesh/CallNGMeshRenderBatches.h
> +				static uint32_t shaderUpdateBit()			{ return 0x1; }
Edit: Fixed in 9863f3b

2018-01-31 17:33 UTC, tobiasrau requested changes
- [x] Should be merged with the actual master.
 - [x] Build checks missing
 - [x] glload is deprecated
 - [x] externals should be stored in a external subdirectory in the plugin, not in the plugins `src` directory
 - [ ] `Readme.md` is empty

2019-07-09 12:31 UTC, tobiasrau commented
Cleaned and splitted into #314 and #315.

2019-07-09 12:31 UTC, closed without merging