Fix transferfunction + new colormaps
UniStuttgart-VISUS/megamol pull request #551
Opened 2020-04-26 18:32 UTC by moritz-h

2020-04-27 07:54 UTC, schulzch requested changes
Adding the amount of supported classes is important. Rest is optional

2020-04-27 07:54 UTC, schulzch commented on plugins/gui/src/TransferFunctionEditor.cpp
> +    std::make_tuple("AccentMap (qualitative)", ColormapAdapter<8, true>(AccentMap)),
This one is just called "Accent" and the amount of classes should be included, e.g. "5-class Accent".

2020-04-27 07:54 UTC, schulzch commented on plugins/gui/src/TransferFunctionEditor.cpp
> -            double it = std::fmod(t * LastIndex, LastIndex);
Nice catch! 👍

2020-04-27 07:54 UTC, schulzch commented on plugins/gui/src/TransferFunctionEditor.cpp
> +std::array<std::tuple<std::string, PresetGenerator>, 20> PRESETS = {
Now that we have more and more color maps, this tuple could/should be split into a struct, e.g..:
```
struct Preset {
	std::string name;
	enum class Scale {
		Sequential,
		Diverging,
		Qualitative
	} scale;
	std::string notice; // harmful, de-pinked, ...
	std::string reference; // ColorBrewer, Paper, ...
};
```
(just an idea)

2020-05-08 15:00 UTC, reinago approved these changes

2020-05-08 15:02 UTC, reinago approved these changes

2020-05-08 15:05 UTC, invor approved these changes

2020-05-08 15:47 UTC, schulzch approved these changes

2020-05-08 15:47 UTC, merged