Replacement of Shader Factory
UniStuttgart-VISUS/megamol pull request #620
Opened 2020-09-03 13:03 UTC by gralkapk

2020-09-21 14:38 UTC, geringsj commented on core/include/mmcore/utility/graphics/GLSLShader.h
> +    ~GLSLShader() { glDeleteShader(_program); }
Is glDeleteShader correct here, or do we want to glDeleteProgram?

2020-09-21 14:40 UTC, geringsj commented on core/include/mmcore/utility/graphics/GLSLShader.h
> +                _uniform_map.emplace(std::make_pair(std::string(name.get(), length),
We could also carry along the uniform type here.

2020-09-21 15:39 UTC, geringsj approved these changes

2020-09-21 15:44 UTC, geringsj requested changes
Fix https://github.com/UniStuttgart-VISUS/megamol/pull/620/files#r492100091

2020-10-01 11:52 UTC, geringsj submitted a review, later dismissed

2021-02-01 13:15 UTC, moritz-h requested changes
Maybe we should discuss the following design choices before merging:
- Should we really name generic Shaders with `*.h` instead of `*.glsl`. Maybe `.glsl` is a better separation from C++ files, also syntax highlighting is may be better with glsl depending on editor.
- What is the purpose of the GLSLShader class within MegaMol? Do we want to remove this in favor of glowl `GLSLProgram`? And if not, why not also move this class to the library?

2021-04-21 16:21 UTC, moritz-h approved these changes

2021-04-21 16:28 UTC, merged