CLI: load default config from executable location
UniStuttgart-VISUS/megamol pull request #817
Opened 2021-06-07 17:20 UTC by geringsj

Load default config from `megamol.exe` directory

2021-06-07 17:38 UTC, moritz-h requested changes
The #ifdef cascade to include filesystem is not needed anymore.
Just do `#include <filesystem>`. We require a modern enough compiler now anyway.

2021-06-07 17:38 UTC, moritz-h commented on frontend/main/src/CLIConfigParsing.cpp
> +static std::string getExecutableDirectory() {
Why not just using std::filesystem:path as return type?

2021-06-08 11:16 UTC, moritz-h approved these changes

2021-06-14 08:17 UTC, tobiasrau approved these changes

2021-06-14 08:17 UTC, merged